name: Deploy Backend to Hugging Face

# This creates a manual button in GitHub Actions so you control deployments
on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd backend
          git init
          git branch -M main
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Manual deploy from GitHub"
          git push --force https://user:$HF_TOKEN@huggingface.co/spaces/Utkarshjain05/qna-doc-backend main